
version: "2"
services:
  webserver:
    image: "devbytom/moodle-php-apache:7.3"
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./assets/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
      - "./assets/web/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
    depends_on:
      - mailhog
    environment:
      MOODLE_DOCKER_DBTYPE: "pgsql"
      MOODLE_DOCKER_DBHOST: "10.0.1.3"
      MOODLE_DOCKER_DBNAME: "kahlo-cc"
      MOODLE_DOCKER_DBUSER: "postgres"
      MOODLE_DOCKER_DBPASS: "dev"
      MOODLE_DOCKER_BROWSER: "firefox"
      MOODLE_DOCKER_WEB_HOST: "edu.kahlo.cc"
      MOODLE_DOCKER_WEB_PORT: "443"
  mailhog:
    image: mailhog/mailhog
  nginx:
    image: devbytom/nginx_kahlo_cc:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    build:
      context: ./nginx/
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
